version: '3.8'
services:
  web:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/app
    - /app/node_modules
    depends_on:
    - mongodb
  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: "test"
      MONGO_INITDB_ROOT_PASSWORD: "test"
      MONGO_INITDB_DATABASE: "test"